// Spell data organized by level for scroll generation
const spellsByLevel = {
    "cantrip": [
        "acid splash",
        "chill touch", 
        "dancing lights",
        "druidcraft",
        "eldritch blast",
        "fire bolt",
        "guidance",
        "light",
        "mage hand",
        "mending",
        "message",
        "minor illusion",
        "poison spray",
        "prestidigitation",
        "produce flame",
        "ray of frost",
        "resistance",
        "sacred flame",
        "shillelagh",
        "shocking grasp",
        "spare the dying",
        "thaumaturgy",
        "true strike",
        "vicious mockery"
    ],
    "1": [
        "alarm",
        "animal friendship",
        "bane",
        "bless",
        "burning hands",
        "charm person",
        "command",
        "comprehend languages",
        "create or destroy water",
        "cure wounds",
        "detect evil and good",
        "detect magic",
        "detect poison and disease",
        "disguise self",
        "divine favor",
        "entangle",
        "expeditious retreat",
        "faerie fire",
        "false life",
        "feather fall",
        "find familiar",
        "fog cloud",
        "goodberry",
        "grease",
        "guiding bolt",
        "healing word",
        "hellish rebuke",
        "heroism",
        "hideous laughter",
        "hunter's mark",
        "identify",
        "illusory script",
        "inflict wounds",
        "jump",
        "longstrider",
        "mage armor",
        "magic missile",
        "protection from evil and good",
        "purify food and drink",
        "sanctuary",
        "shield",
        "shield of faith",
        "silent image",
        "sleep",
        "speak with animals",
        "thunderwave",
        "unseen servant"
    ],
    "2": [
        "acid arrow",
        "aid",
        "alter self",
        "animal messenger",
        "arcane lock",
        "arcanist's magic aura",
        "augury",
        "barkskin",
        "blindness/deafness",
        "blur",
        "branding smite",
        "calm emotions",
        "continual flame",
        "darkness",
        "darkvision",
        "detect thoughts",
        "enhance ability",
        "enlarge/reduce",
        "enthrall",
        "find steed",
        "find traps",
        "flame blade",
        "flaming sphere",
        "gentle repose",
        "gust of wind",
        "heat metal",
        "hold person",
        "invisibility",
        "knock",
        "lesser restoration",
        "levitate",
        "locate animals or plants",
        "locate object",
        "magic mouth",
        "magic weapon",
        "mirror image",
        "misty step",
        "moonbeam",
        "pass without trace",
        "prayer of healing",
        "protection from poison",
        "ray of enfeeblement",
        "rope trick",
        "scorching ray",
        "see invisibility",
        "shatter",
        "silence",
        "spider climb",
        "spike growth",
        "spiritual weapon",
        "suggestion",
        "warding bond",
        "web"
    ],
    "3": [
        "animate dead",
        "beacon of hope",
        "bestow curse",
        "blink",
        "call lightning",
        "clairvoyance",
        "conjure animals",
        "counterspell",
        "create food and water",
        "daylight",
        "dispel magic",
        "fear",
        "fireball",
        "fly",
        "gaseous form",
        "glyph of warding",
        "haste",
        "hypnotic pattern",
        "lightning bolt",
        "magic circle",
        "major image",
        "mass healing word",
        "meld into stone",
        "nondetection",
        "phantom steed",
        "plant growth",
        "protection from energy",
        "remove curse",
        "revivify",
        "sending",
        "sleet storm",
        "slow",
        "speak with dead",
        "speak with plants",
        "spirit guardians",
        "stinking cloud",
        "tiny hut",
        "tongues",
        "vampiric touch",
        "water breathing",
        "water walk",
        "wind wall"
    ],
    "4": [
        "arcane eye",
        "banishment",
        "black tentacles",
        "blight",
        "compulsion",
        "confusion",
        "conjure minor elementals",
        "conjure woodland beings",
        "control water",
        "death ward",
        "dimension door",
        "divination",
        "dominate beast",
        "fabricate",
        "faithful hound",
        "fire shield",
        "freedom of movement",
        "giant insect",
        "greater invisibility",
        "guardian of faith",
        "hallucinatory terrain",
        "ice storm",
        "locate creature",
        "phantasmal killer",
        "polymorph",
        "private sanctum",
        "resilient sphere",
        "secret chest",
        "stone shape",
        "stoneskin",
        "wall of fire"
    ],
    "5": [
        "animate objects",
        "antilife shell",
        "awaken",
        "cloudkill",
        "commune",
        "commune with nature",
        "cone of cold",
        "conjure elemental",
        "contact other plane",
        "contagion",
        "creation",
        "dispel evil and good",
        "dominate person",
        "dream",
        "flame strike",
        "geas",
        "greater restoration",
        "hallow",
        "hold monster",
        "insect plague",
        "legend lore",
        "mass cure wounds",
        "mislead",
        "modify memory",
        "passwall",
        "planar binding",
        "raise dead",
        "reincarnate",
        "scrying",
        "seeming",
        "telekinesis",
        "telepathic bond",
        "teleportation circle",
        "tree stride",
        "wall of force",
        "wall of stone"
    ],
    "6": [
        "blade barrier",
        "chain lightning",
        "circle of death",
        "conjure fey",
        "contingency",
        "create undead",
        "disintegrate",
        "eyebite",
        "find the path",
        "flesh to stone",
        "forbiddance",
        "freezing sphere",
        "globe of invulnerability",
        "guards and wards",
        "harm",
        "heal",
        "heroes' feast",
        "instant summons",
        "irresistible dance",
        "magic jar",
        "mass suggestion",
        "move earth",
        "planar ally",
        "programmed illusion",
        "sunbeam",
        "transport via plants",
        "true seeing",
        "wall of ice",
        "wall of thorns",
        "wind walk",
        "word of recall"
    ],
    "7": [
        "arcane sword",
        "conjure celestial",
        "delayed blast fireball",
        "divine word",
        "etherealness",
        "finger of death",
        "fire storm",
        "forcecage",
        "magnificent mansion",
        "mirage arcane",
        "plane shift",
        "prismatic spray",
        "project image",
        "regenerate",
        "resurrection",
        "reverse gravity",
        "sequester",
        "simulacrum",
        "symbol",
        "teleport"
    ],
    "8": [
        "animal shapes",
        "antimagic field",
        "antipathy/sympathy",
        "clone",
        "control weather",
        "demiplane",
        "dominate monster",
        "earthquake",
        "feeblemind",
        "glibness",
        "holy aura",
        "incendiary cloud",
        "maze",
        "mind blank",
        "power word stun",
        "sunburst"
    ],
    "9": [
        "astral projection",
        "foresight",
        "gate",
        "imprisonment",
        "mass heal",
        "meteor swarm",
        "power word kill",
        "prismatic wall",
        "shapechange",
        "storm of vengeance",
        "time stop",
        "true polymorph",
        "true resurrection",
        "weird",
        "wish"
    ]
};

// Spell level to rarity/DC/attack mapping
const scrollStats = {
    "cantrip": { rarity: "Common", dc: 13, attack: 5, price: 30 },
    "1": { rarity: "Common", dc: 13, attack: 5, price: 50 },
    "2": { rarity: "Uncommon", dc: 13, attack: 5, price: 200 },
    "3": { rarity: "Uncommon", dc: 15, attack: 7, price: 300 },
    "4": { rarity: "Rare", dc: 15, attack: 7, price: 2000 },
    "5": { rarity: "Rare", dc: 17, attack: 9, price: 3000 },
    "6": { rarity: "Very Rare", dc: 17, attack: 9, price: 20000 },
    "7": { rarity: "Very Rare", dc: 18, attack: 10, price: 25000 },
    "8": { rarity: "Very Rare", dc: 18, attack: 10, price: 30000 },
    "9": { rarity: "Legendary", dc: 19, attack: 11, price: 100000 }
};

// Rarity to spell levels mapping
const rarityToLevels = {
    "common": ["cantrip", "1"],
    "uncommon": ["2", "3"],
    "rare": ["4", "5"],
    "very-rare": ["6", "7", "8"],
    "legendary": ["9"]
};

// Function to convert spell name to URL-friendly format
function spellNameToUrl(spellName) {
    return spellName
        .toLowerCase()
        .replace(/'/g, '') // Remove apostrophes
        .replace(/\//g, '') // Remove slashes
        .replace(/\s+/g, '-') // Replace spaces with hyphens
        .replace(/[^a-z0-9-]/g, ''); // Remove any other special characters
}

// Function to get spell link
function getSpellLink(spellName) {
    const urlName = spellNameToUrl(spellName);
    return `../../spells/html/5.2_srd_(d&d_2024)/${urlName}.html`;
}