// Common condition list used across multiple generators
// This is a shared data file to maintain consistency across all tools

const commonConditions = [
  'aberrant',
  'abyssal',
  'acidic',
  'ancient',
  'astral',
  'bladed',
  'bloody',
  'buried',
  'cracked',
  'crumbling',
  'crystalline',
  'cursed',
  'cyclopean',
  'defiled',
  'dreamscape',
  'earthen',
  'eldritch',
  'emerald',
  'entombed',
  'ethereal',
  'flaming',
  'floating',
  'flooded',
  'foggy',
  'frozen',
  'glass',
  'glowing',
  'glyphed',
  'hallowed',
  'haunted',
  'holy',
  'infested',
  'lightning-touched',
  'moontouched',
  'musical',
  'necrotic',
  'obsidian',
  'oozing',
  'opal',
  'poisonous',
  'psionic',
  'radiant',
  'ruby',
  'ruined',
  'sapphire',
  'shadowy',
  'spiked',
  'startouched',
  'stormy',
  'temporal',
  'titanic',
  'twilight',
  'unearthed',
  'unhallowed',
  'unholy'
];

// Export for use in generators
if (typeof module !== 'undefined' && module.exports) {
  module.exports = commonConditions;
}