// Minimal spell index for scroll generation
// Only contains name, level, and source - much smaller than full spell data

const spellIndex = {
  "dmag": {
    "4": [
      "Abhorrent Apparition",
      "Binding Oath",
      "Black Hand",
      "Blade of my Brother",
      "Blood Puppet",
      "Blood Spoor",
      "Blood and Steel",
      "Boiling Blood",
      "Brittling",
      "By the Light of the Watchful Moon",
      "Chains of Torment",
      "Chaotic Form",
      "Consult the Storm",
      "Cursed Gift",
      "Desiccating Breath",
      "Deva\u2019s Wings",
      "Doom of Serpent Coils",
      "Doom of the Earthen Maw",
      "Earthskimmer",
      "Echoes of Steel",
      "Emanation of Yoth",
      "Endow Attribute",
      "Energy Foreknowledge",
      "Evercold",
      "Flame Wave",
      "Flickering Fate",
      "Fluctuating Alignment",
      "Fusillade of Ice",
      "Green Decay",
      "Harry",
      "Heart-Seeking Arrow",
      "Hide in One\u2019s Shadow",
      "Hunger of Leng",
      "Hunting Stand",
      "Inspiring Speech",
      "Instant Siege Weapon",
      "Keening Wail",
      "Labyrinth Mastery",
      "Lava Stone",
      "Looping Trail",
      "Lovesick",
      "Moon Trap",
      "Nether Weapon",
      "Night Terrors",
      "Not Dead Yet",
      "Pitfall",
      "Power Word Pain",
      "Quick Time",
      "Quicksilver Mantle",
      "Raid the Lair",
      "Ray of Alchemical Negation",
      "Ray of Life Suppression",
      "Reposition",
      "Reset",
      "Sand Ship",
      "Scale Rot",
      "Scry Ambush",
      "Searing Sun",
      "Shadow Monsters",
      "Shadowy Retribution",
      "Shroud of Death",
      "Snow Boulder",
      "Spinning Axes",
      "Staff of Violet Fire",
      "Steam Blast",
      "Storm of Wings",
      "Time Vortex",
      "Torrent of Fire",
      "Visage of Madness",
      "Wild Shield",
      "Wintry Glide",
      "Yellow Sign"
    ],
    "3": [
      "Accelerate",
      "Alone",
      "Anticipate Arcana",
      "Aspect of the Serpent",
      "Aura of Protection or Destruction",
      "Blade of Wrath",
      "Blood Armor",
      "Blood Offering",
      "Booster Shot",
      "Breeze Compass",
      "Call Shadow Mastiff",
      "Calm of the Storm",
      "Catch the Breath",
      "Chilling Words",
      "Closing In",
      "Compelled Movement",
      "Compelling Fate",
      "Confound Senses",
      "Conjure Undead",
      "Curse of Incompetence",
      "Cynophobia",
      "Dark Heraldry",
      "Delayed Healing",
      "Demon Within",
      "Dimensional Shove",
      "Doom of Blue Crystal",
      "Doom of Dancing Blades",
      "Doom of Disenchantment",
      "Drown",
      "Dryad\u2019s Kiss",
      "Entropic Damage Field",
      "Flesh to Paper",
      "Freeze Blood",
      "Freezing Fog",
      "Frostbitten Fingers",
      "Frozen Razors",
      "Gloomwrought Barrier",
      "Gluey Globule",
      "Going in Circles",
      "Hedren\u2019s Birds of Clay",
      "Hematomancy",
      "Hero's Steel",
      "Impending Ally",
      "Innocuous Aspect",
      "Ire of the Mountain",
      "Legion",
      "Legion of Rabid Squirrels",
      "Lesser Maze",
      "Life Sense",
      "Life from Death",
      "Mass Hobble Mount",
      "Mind Exchange",
      "Mire",
      "Monstrous Empathy",
      "Nightfall",
      "Outflanking Boon",
      "Phantom Dragon",
      "Potency of the Pack",
      "Protective Ice",
      "Reaver Spirit",
      "Riptide",
      "Rune of Imprisonment",
      "Salt Lash",
      "Seeping Death",
      "Shadow Trove",
      "Sidestep Arrow",
      "Sir Mittinz\u2019s Move Curse",
      "Sleep of the Deep",
      "Song of the Forest",
      "Spiteful Weapon",
      "Steal Warmth",
      "Sudden Dawn",
      "Surge Dampener",
      "Targeting Foreknowledge",
      "Thousand Darts",
      "Throes of Ecstasy",
      "Thunderclap",
      "Thunderous Wave",
      "Tongue of Sand",
      "Touch of the Unliving",
      "Tracer",
      "Unseen Strangler",
      "Vital Mark",
      "Void Strike"
    ],
    "7": [
      "Acid Gate",
      "Amplify Gravity",
      "Aspect of the Dragon",
      "Blizzard",
      "Celebration",
      "Conjure Greater Spectral Dead",
      "Conjure Shadow Titan",
      "Conjure Voidborn",
      "Create Thunderstaff",
      "Curse of Dust",
      "Curse of the Grave",
      "Death God\u2019s Touch",
      "Defile Healing",
      "Glacial Fog",
      "Ice Soldiers",
      "Icy Grasp of the Void",
      "Last Rays of the Dying Sun",
      "Legend Killer",
      "Right the Stars",
      "Ring Ward",
      "Seal of Sanctuary",
      "Sign of Koth",
      "Starry Vision",
      "Symbol of Sorcery",
      "Talons of a Hungry Land",
      "Triumph of Ice",
      "Uncontrollable Transformation",
      "Volley Shield",
      "Walking Wall"
    ],
    "5": [
      "Acid Rain",
      "Ancient Shade",
      "Blazing Chariot",
      "Bottled Arcana",
      "Chains of the Goddess",
      "Clash of Glaciers",
      "Claws of the Earth Dragon",
      "Conjure Fey Hound",
      "Conjure Minor Voidborn",
      "Curse Ring",
      "Curse of Yig",
      "Dark Dementing",
      "Dragon Breath",
      "Eidetic Memory",
      "Eldritch Communion",
      "Energy Absorption",
      "Essence Instability",
      "Exsanguinate",
      "Exsanguinating Cloud",
      "Fey Crown",
      "Frostbite",
      "Grasp of the Tupilak",
      "Harrying Hounds",
      "Holy Ground",
      "Ice Fortress",
      "Instant Fortification",
      "Killing Fields",
      "Kiss of the Succubus",
      "Labyrinthine Howl",
      "Lay to Rest",
      "Living Shadows",
      "Maim",
      "Mass Surge Dampener",
      "Not This Day!",
      "Primal Infusion",
      "Prismatic Ray",
      "Rain of Blades",
      "Sanguine Horror",
      "See Beyond",
      "Starfall",
      "Summon Eldritch Servitor",
      "Surprise Blessing",
      "Thunderstorm",
      "Tongue Tied",
      "Wall of Time"
    ],
    "1": [
      "Adjust Position",
      "Agonizing Mark",
      "Alter Arrow\u2019s Fortune",
      "Analyze Device",
      "Ancestor\u2019s Strength",
      "Anchoring Rope",
      "Angelic Guardian",
      "Anticipate Weakness",
      "Auspicious Warning",
      "Avoid Grievous Injury",
      "Black Ribbons",
      "Bleed",
      "Blood Scarab",
      "Bloodhound",
      "Bloody Hands",
      "Bloody Smite",
      "Bolster Undead",
      "Bottomless Stomach",
      "Breathtaking Wind",
      "Broken Charge",
      "Candle\u2019s Insight",
      "Chronal Lance",
      "Circle of Wind",
      "Cloak of Shadow",
      "Cobra Fangs",
      "Converse With Dragon",
      "Cure Beast",
      "Deep Breath",
      "Disquieting Gaze",
      "Doom of the Cracked Shield",
      "Draconic Smite",
      "Earworm Melody",
      "Feather Field",
      "Find Kin",
      "Fire Under the Tongue",
      "Flurry",
      "Forest Native",
      "Foretell Distraction",
      "Freeze Potion",
      "Gird the Spirit",
      "Gliding Step",
      "Goat's Hoof Charm",
      "Gordolay\u2019s Pleasant Aroma",
      "Guest of Honor",
      "Guiding Star",
      "Hard Heart",
      "Heart to Heart",
      "Hobble Mount",
      "Hone Blade",
      "Hunter's Endurance",
      "Icicle Daggers",
      "Ill-Fated Word",
      "Illuminate Spoor",
      "Insightful Maneuver",
      "Kareef\u2019s Entreaty",
      "Kobold\u2019s Fury",
      "Life Transference Arrow",
      "Litany of Sure Hands",
      "Maw of Needles",
      "Mosquito Bane",
      "Mud Pack",
      "Pendulum",
      "Protection from the Void",
      "Ring Strike",
      "Scentless",
      "Screaming Ray",
      "Seer\u2019s Reaction",
      "Shadow Armor",
      "Shadow Hands",
      "Slippery Fingers",
      "Snowy Coat",
      "Speak with Inanimate Object",
      "Spur Mount",
      "Stanch",
      "Thin the Ice",
      "Thunderous Charge",
      "Tidal Barrier",
      "Tireless",
      "Tree Speak",
      "Trick Question",
      "Twist the Skein",
      "Undermine Armor",
      "Unluck On That",
      "Voorish Sign",
      "Waft",
      "Weapon of Blood",
      "Wind Tunnel",
      "Withered Sight",
      "Wolfsong",
      "Writhing Arms"
    ],
    "9": [
      "Afflict Line",
      "Blood to Acid",
      "Forest Sanctuary",
      "Form of the Gods",
      "Greater Maze",
      "Greater Seal of Sanctuary",
      "Mammon\u2019s Due",
      "Pyroclasm",
      "Star's Heart",
      "Time in a Bottle",
      "Umbral Storm",
      "Unleash Effigy",
      "Void Rift"
    ],
    "6": [
      "Alchemical Form",
      "Ally Aegis",
      "Animate Greater Undead",
      "Avronin\u2019s Astral Assembly",
      "Become Nightwing",
      "Black Well",
      "Catapult",
      "Chaotic World",
      "Conjure Forest Defender",
      "Curse of Boreas",
      "Enchant Ring",
      "Encroaching Shadows",
      "Entomb",
      "Extract Knowledge",
      "Fault Line",
      "Firewalk",
      "Heavenly Crown",
      "Icy Manipulation",
      "Life Drain",
      "Time Loop",
      "Walk the Twisted Path",
      "Warp Mind and Matter",
      "Winter's Radiance",
      "Winterdark"
    ],
    "0": [
      "Ale-dritch Blast",
      "Animated Scroll",
      "Benediction",
      "Biting Arrow",
      "Black Goat\u2019s Blessing",
      "Bless the Dead",
      "Blood Tide",
      "Brimstone Infusion",
      "Caustic Touch",
      "Claws of Darkness",
      "Clockwork Bolt",
      "Crushing Curse",
      "Dark Maw",
      "Decay",
      "Douse Light",
      "Dragon Roar",
      "Encrypt / Decrypt",
      "Fist of Iron",
      "Hamstring",
      "Hoarfrost",
      "Hobble",
      "Iron Hand",
      "Memento Mori",
      "Misstep",
      "Puff of Smoke",
      "Pummelstone",
      "Quicken",
      "Scribe",
      "Semblance of Dread",
      "Shadow Bite",
      "Shadow Blindness",
      "Shiver",
      "Silhouette",
      "Starburst",
      "Thunder Bolt",
      "Tree Heal",
      "Wind Lash",
      "Word of Misfortune"
    ],
    "2": [
      "Althea\u2019s Travel Tent",
      "Animate Ghoul",
      "Anticipate Attack",
      "As You Were",
      "Ashen Memories",
      "Bad Timing",
      "Batsense",
      "Beguiling Bet",
      "Bestial Fury",
      "Bitter Chains",
      "Black Swan Storm",
      "Bleating Call",
      "Blessed Halo",
      "Blood Lure",
      "Bloodshot",
      "Boiling Oil",
      "Boreas\u2019s Breath",
      "By the Light of the Moon",
      "Carmello-Volta\u2019s Irksome Preserves",
      "Caustic Blood",
      "Champion\u2019s Weapon",
      "Chaotic Vitality",
      "Clearing the Field",
      "Comprehend Wild Shape",
      "Conjure Scarab Swarm",
      "Conjure Spectral Dead",
      "Creeping Ice",
      "Crushing Trample",
      "Daggerhawk",
      "Dark Path",
      "Darkbolt",
      "Dead Walking",
      "Decelerate",
      "Delay Potion",
      "Destructive Resonance",
      "Detect Dragons",
      "Distracting Divination",
      "Distraction Cascade",
      "Doom of Consuming Fire",
      "Doom of the Slippery Rogue",
      "Ectoplasm",
      "Elemental Horns",
      "Elemental Twist",
      "Enhance Greed",
      "Feather Travel",
      "Fire Darts",
      "Frenzied Bolt",
      "Furious Hooves",
      "Gear Barrage",
      "Glyph of Shifting",
      "Grudge Match",
      "Heartache",
      "Heartstop",
      "Heartstrike",
      "Ice Hammer",
      "Instant Snare",
      "Lacerate",
      "Lair Sense",
      "Lock Armor",
      "Maddening Whispers",
      "Mark Prey",
      "Mephitic Croak",
      "Mist of Wonders",
      "Negative Image",
      "Nip at the Heels",
      "Orb of Light",
      "Poisoned Volley",
      "Power Word Kneel",
      "Reverberate",
      "Revive Beast",
      "Rolling Thunder",
      "Rotting Corpse",
      "Sculpt Snow",
      "Shade",
      "Shadow Puppets",
      "Shadows Brought to Light",
      "Shared Sacrifice",
      "Sheen of Ice",
      "Shifting the Odds",
      "Slither",
      "Snow Fort",
      "Spin",
      "Stench of Rot",
      "Thunderous Stampede",
      "Time Step",
      "Timely Distraction",
      "Treasure Chasm",
      "Tree Running",
      "Trench",
      "Unholy Defiance",
      "Vine Trestle",
      "Vomit Tentacles",
      "Warning Shout",
      "Weiler\u2019s Ward",
      "Wresting Wind"
    ],
    "8": [
      "Arcane Sight",
      "Awaken Object",
      "Black Sunshine",
      "Bloom",
      "Caustic Torrent",
      "Costly Victory",
      "Create Ring Servant",
      "Deadly Sting",
      "Desolation",
      "Disruptive Aura",
      "Ghoul King\u2019s Cloak",
      "Glacial Cascade",
      "Glimpse of the Void",
      "Harsh Light of Summer\u2019s Glare",
      "Life Hack",
      "Malevolent Waves",
      "Paragon of Chaos",
      "Quintessence",
      "Seed of Destruction",
      "Steam Whistle",
      "Summon Star",
      "Time Jump",
      "Time Slippage",
      "Wind of the Hereafter"
    ]
  },
  "a5e": {
    "4": [
      "Accelerando",
      "Arcane Eye",
      "Banishment",
      "Black Tentacles",
      "Blight",
      "Charm Monster",
      "Confusion",
      "Conjure Minor Elementals",
      "Conjure Woodland Beings",
      "Control Water",
      "Death Ward",
      "Dimension Door",
      "Divination",
      "Dominate Beast",
      "Fabricate",
      "Faithful Hound",
      "Fire Shield",
      "Freedom of Movement",
      "Giant Insect",
      "Greater Invisibility",
      "Guardian of Faith",
      "Hallucinatory Terrain",
      "Ice Storm",
      "Locate Creature",
      "Mindshield",
      "Phantasmal Killer",
      "Polymorph",
      "Private Sanctum",
      "Rage of the Meek",
      "Resilient Sphere",
      "Secret Chest",
      "Stone Shape",
      "Stoneskin",
      "Tearful Sonnet",
      "Wall of Fire"
    ],
    "2": [
      "Acid Arrow",
      "Aid",
      "Alter Self",
      "Animal Messenger",
      "Arcane Lock",
      "Arcanist's Magic Aura",
      "Augury",
      "Barkskin",
      "Blindness/Deafness",
      "Blur",
      "Calm Emotions",
      "Continual Flame",
      "Darkness",
      "Darkvision",
      "Deadweight",
      "Detect Thoughts",
      "Enhance Ability",
      "Enlarge/Reduce",
      "Enthrall",
      "Find Steed",
      "Find Traps",
      "Flame Blade",
      "Flaming Sphere",
      "Flex",
      "Force of Will",
      "Gentle Repose",
      "Gust of Wind",
      "Heat Metal",
      "Hold Person",
      "Invigorated Strikes",
      "Invisibility",
      "Knock",
      "Lemure Transformation",
      "Lesser Restoration",
      "Levitate",
      "Locate Animals or Plants",
      "Locate Object",
      "Magic Mouth",
      "Magic Weapon",
      "Mental Grip",
      "Mirror Image",
      "Misty Step",
      "Moonbeam",
      "Pass Without Trace",
      "Prayer of Healing",
      "Protection from Energy",
      "Protection from Poison",
      "Ray of Enfeeblement",
      "Rope Trick",
      "Scorching Ray",
      "See Invisibility",
      "Seed Bomb",
      "Shatter",
      "Shattering Barrage",
      "Silence",
      "Sleet Storm",
      "Soulwrought Fists",
      "Spider Climb",
      "Spike Growth",
      "Spiritual Weapon",
      "Suggestion",
      "Warding Bond",
      "Web",
      "Zone of Truth"
    ],
    "0": [
      "Acid Splash",
      "Altered Strike",
      "Arcane Muscles",
      "Calculate",
      "Chill Touch",
      "Circular Breathing",
      "Dancing Lights",
      "Druidcraft",
      "Fire Bolt",
      "Friends",
      "Grapevine",
      "Guidance",
      "Light",
      "Mage Hand",
      "Mending",
      "Message",
      "Minor Illusion",
      "Pestilence",
      "Prestidigitation",
      "Produce Flame",
      "Ray of Frost",
      "Resistance",
      "Sacred Flame",
      "Shillelagh",
      "Shocking Grasp",
      "Spare the Dying",
      "Thaumaturgy",
      "True Strike",
      "Vicious Mockery"
    ],
    "1": [
      "Air Wave",
      "Alarm",
      "Animal Friendship",
      "Arcane Riposte",
      "Bane",
      "Bless",
      "Burning Hands",
      "Calculated Retribution",
      "Ceremony",
      "Charm Person",
      "Color Spray",
      "Command",
      "Comprehend Languages",
      "Corpse Explosion",
      "Create or Destroy Water",
      "Cure Wounds",
      "Detect Evil and Good",
      "Detect Magic",
      "Detect Poison and Disease",
      "Disguise Self",
      "Divine Favor",
      "Dramatic Sting",
      "Earth Barrier",
      "Entangle",
      "Expeditious Retreat",
      "Faerie Fire",
      "False Life",
      "Feather Fall",
      "Find Familiar",
      "Floating Disk",
      "Fog Cloud",
      "Force Punch",
      "Goodberry",
      "Grease",
      "Guiding Bolt",
      "Harmonic Resonance",
      "Healing Word",
      "Heroism",
      "Hideous Laughter",
      "Identify",
      "Illusory Script",
      "Inflict Wounds",
      "Jump",
      "Longstrider",
      "Mage Armor",
      "Magic Missile",
      "Phantasmal Talons",
      "Protection from Evil and Good",
      "Purify Food and Drink",
      "Sanctuary",
      "Searing Equation",
      "Shield",
      "Shield of Faith",
      "Silent Image",
      "Sleep",
      "Speak with Animals",
      "Thunderwave",
      "Traveler's Ward",
      "Unseen Servant",
      "Wind Up"
    ],
    "7": [
      "Angel Paradox",
      "Arcane Sword",
      "Conjure Celestial",
      "Delayed Blast Fireball",
      "Divine Word",
      "Enrage Architecture",
      "Etherealness",
      "Finger of Death",
      "Fire Storm",
      "Forcecage",
      "Inescapable Malady",
      "Magnificent Mansion",
      "Mirage Arcane",
      "Plane Shift",
      "Prismatic Spray",
      "Project Image",
      "Regenerate",
      "Resurrection",
      "Reverse Gravity",
      "Sequester",
      "Simulacrum",
      "Sporesight",
      "Symbol",
      "Teleport",
      "Unholy Star"
    ],
    "8": [
      "Animal Shapes",
      "Antimagic Field",
      "Antipathy/Sympathy",
      "Clone",
      "Control Weather",
      "Demiplane",
      "Dominate Monster",
      "Earthquake",
      "Feeblemind",
      "Glibness",
      "Heart of Dis",
      "Holy Aura",
      "Incendiary Cloud",
      "Maze",
      "Mind Blank",
      "Power Word Stun",
      "Sunburst"
    ],
    "3": [
      "Animate Dead",
      "Aspect of the Moon",
      "Battlecry Ballad",
      "Beacon of Hope",
      "Bestow Curse",
      "Blink",
      "Blood-Writ Bargain",
      "Call Lightning",
      "Clairvoyance",
      "Cobra's Spit",
      "Conjure Animals",
      "Counterspell",
      "Create Food and Water",
      "Crushing Haymaker",
      "Darklight",
      "Daylight",
      "Dispel Magic",
      "Fear",
      "Fireball",
      "Fly",
      "Gaseous Form",
      "Glyph of Warding",
      "Haste",
      "Hypnotic Pattern",
      "Lightning Bolt",
      "Magic Circle",
      "Major Image",
      "Mass Healing Word",
      "Meld Into Stone",
      "Nondetection",
      "Phantom Steed",
      "Plant Growth",
      "Poison Skin",
      "Remove Curse",
      "Revivify",
      "Sending",
      "Slow",
      "Speak with Dead",
      "Speak with Plants",
      "Spirit Guardians",
      "Stinking Cloud",
      "Tiny Hut",
      "Tongues",
      "Vampiric Touch",
      "Venomous Succor",
      "Water Breathing",
      "Water Walk",
      "Whirlwind Kick",
      "Wind Wall"
    ],
    "5": [
      "Animate Objects",
      "Antilife Shell",
      "Arcane Hand",
      "Awaken",
      "Cloudkill",
      "Commune",
      "Commune with Nature",
      "Cone of Cold",
      "Conjure Elemental",
      "Contact Other Plane",
      "Contagion",
      "Creation",
      "Dispel Evil and Good",
      "Dominate Person",
      "Dream",
      "Eldritch Cube",
      "Flame Strike",
      "Geas",
      "Greater Restoration",
      "Hallow",
      "Hold Monster",
      "Insect Plague",
      "Legend Lore",
      "Mass Cure Wounds",
      "Mislead",
      "Modify Memory",
      "Passwall",
      "Planar Binding",
      "Raise Dead",
      "Reincarnate",
      "Scrying",
      "Seeming",
      "Storm Kick",
      "Telekinesis",
      "Telepathic Bond",
      "Teleportation Circle",
      "Tree Stride",
      "Wall of Force",
      "Wall of Stone",
      "Warrior's Instincts"
    ],
    "9": [
      "Astral Projection",
      "Foresight",
      "Forest Army",
      "Gate",
      "Imprisonment",
      "Mass Heal",
      "Meteor Swarm",
      "Power Word Kill",
      "Prismatic Wall",
      "Raise Hell",
      "Shapechange",
      "Storm of Vengeance",
      "Time Stop",
      "True Polymorph",
      "True Resurrection",
      "Weird",
      "Wish",
      "Writhing Transformation"
    ],
    "6": [
      "Blade Barrier",
      "Chain Lightning",
      "Circle of Death",
      "Conjure Fey",
      "Contingency",
      "Create Undead",
      "Disintegrate",
      "Eyebite",
      "Find the Path",
      "Flesh to Stone",
      "Forbiddance",
      "Freezing Sphere",
      "Globe of Invulnerability",
      "Guards and Wards",
      "Harm",
      "Heal",
      "Heroes' Feast",
      "Infernal Weapon",
      "Instant Summons",
      "Irresistible Dance",
      "Magic Jar",
      "Mass Suggestion",
      "Move Earth",
      "Planar Ally",
      "Programmed Illusion",
      "Sunbeam",
      "Transport via Plants",
      "True Seeing",
      "Wall of Flesh",
      "Wall of Ice",
      "Wall of Thorns",
      "Wind Walk",
      "Word of Recall",
      "Wormway"
    ]
  },
  "wotc-srd": {
    "2": [
      "Acid Arrow",
      "Aid",
      "Alter Self",
      "Animal Messenger",
      "Arcane Lock",
      "Arcanist's Magic Aura",
      "Augury",
      "Barkskin",
      "Blindness/Deafness",
      "Blur",
      "Branding Smite",
      "Calm Emotions",
      "Continual Flame",
      "Darkness",
      "Darkvision",
      "Detect Thoughts",
      "Enhance Ability",
      "Enlarge/Reduce",
      "Enthrall",
      "Find Steed",
      "Find Traps",
      "Flame Blade",
      "Flaming Sphere",
      "Gentle Repose",
      "Gust of Wind",
      "Heat Metal",
      "Hold Person",
      "Invisibility",
      "Knock",
      "Lesser Restoration",
      "Levitate",
      "Locate Animals or Plants",
      "Locate Object",
      "Magic Mouth",
      "Magic Weapon",
      "Mirror Image",
      "Misty Step",
      "Moonbeam",
      "Pass without Trace",
      "Prayer of Healing",
      "Protection from Poison",
      "Ray of Enfeeblement",
      "Rope Trick",
      "Scorching Ray",
      "See Invisibility",
      "Shatter",
      "Silence",
      "Spider Climb",
      "Spike Growth",
      "Spiritual Weapon",
      "Suggestion",
      "Warding Bond",
      "Web",
      "Zone of Truth"
    ],
    "0": [
      "Acid Splash",
      "Chill Touch",
      "Dancing Lights",
      "Druidcraft",
      "Eldritch Blast",
      "Fire Bolt",
      "Guidance",
      "Light",
      "Mage Hand",
      "Mending",
      "Message",
      "Minor Illusion",
      "Poison Spray",
      "Prestidigitation",
      "Produce Flame",
      "Ray of Frost",
      "Resistance",
      "Sacred Flame",
      "Shillelagh",
      "Shocking Grasp",
      "Spare the Dying",
      "Thaumaturgy",
      "True Strike",
      "Vicious Mockery"
    ],
    "1": [
      "Alarm",
      "Animal Friendship",
      "Bane",
      "Bless",
      "Burning Hands",
      "Charm Person",
      "Color Spray",
      "Command",
      "Comprehend Languages",
      "Create or Destroy Water",
      "Cure Wounds",
      "Detect Evil and Good",
      "Detect Magic",
      "Detect Poison and Disease",
      "Disguise Self",
      "Divine Favor",
      "Entangle",
      "Expeditious Retreat",
      "Faerie Fire",
      "False Life",
      "Feather Fall",
      "Find Familiar",
      "Floating Disk",
      "Fog Cloud",
      "Goodberry",
      "Grease",
      "Guiding Bolt",
      "Healing Word",
      "Hellish Rebuke",
      "Heroism",
      "Hideous Laughter",
      "Hunter's Mark",
      "Identify",
      "Illusory Script",
      "Inflict Wounds",
      "Jump",
      "Longstrider",
      "Mage Armor",
      "Magic Missile",
      "Protection from Evil and Good",
      "Purify Food and Drink",
      "Sanctuary",
      "Shield",
      "Shield of Faith",
      "Silent Image",
      "Sleep",
      "Speak with Animals",
      "Thunderwave",
      "Unseen Servant"
    ],
    "8": [
      "Animal Shapes",
      "Antimagic Field",
      "Antipathy/Sympathy",
      "Clone",
      "Control Weather",
      "Demiplane",
      "Dominate Monster",
      "Earthquake",
      "Feeblemind",
      "Glibness",
      "Holy Aura",
      "Incendiary Cloud",
      "Maze",
      "Mind Blank",
      "Power Word Stun",
      "Sunburst"
    ],
    "3": [
      "Animate Dead",
      "Beacon of Hope",
      "Bestow Curse",
      "Blink",
      "Call Lightning",
      "Clairvoyance",
      "Conjure Animals",
      "Counterspell",
      "Create Food and Water",
      "Daylight",
      "Dispel Magic",
      "Fear",
      "Fireball",
      "Fly",
      "Gaseous Form",
      "Glyph of Warding",
      "Haste",
      "Hypnotic Pattern",
      "Lightning Bolt",
      "Magic Circle",
      "Major Image",
      "Mass Healing Word",
      "Meld into Stone",
      "Nondetection",
      "Phantom Steed",
      "Plant Growth",
      "Protection from Energy",
      "Remove Curse",
      "Revivify",
      "Sending",
      "Sleet Storm",
      "Slow",
      "Speak with Dead",
      "Speak with Plants",
      "Spirit Guardians",
      "Stinking Cloud",
      "Tiny Hut",
      "Tongues",
      "Vampiric Touch",
      "Water Breathing",
      "Water Walk",
      "Wind Wall"
    ],
    "5": [
      "Animate Objects",
      "Antilife Shell",
      "Arcane Hand",
      "Awaken",
      "Cloudkill",
      "Commune",
      "Commune with Nature",
      "Cone of Cold",
      "Conjure Elemental",
      "Contact Other Plane",
      "Contagion",
      "Creation",
      "Dispel Evil and Good",
      "Dominate Person",
      "Dream",
      "Flame Strike",
      "Geas",
      "Greater Restoration",
      "Hallow",
      "Hold Monster",
      "Insect Plague",
      "Legend Lore",
      "Mass Cure Wounds",
      "Mislead",
      "Modify Memory",
      "Passwall",
      "Planar Binding",
      "Raise Dead",
      "Reincarnate",
      "Scrying",
      "Seeming",
      "Telekinesis",
      "Telepathic Bond",
      "Teleportation Circle",
      "Tree Stride",
      "Wall of Force",
      "Wall of Stone"
    ],
    "4": [
      "Arcane Eye",
      "Banishment",
      "Black Tentacles",
      "Blight",
      "Compulsion",
      "Confusion",
      "Conjure Minor Elementals",
      "Conjure Woodland Beings",
      "Control Water",
      "Death Ward",
      "Dimension Door",
      "Divination",
      "Dominate Beast",
      "Fabricate",
      "Faithful Hound",
      "Fire Shield",
      "Freedom of Movement",
      "Giant Insect",
      "Greater Invisibility",
      "Guardian of Faith",
      "Hallucinatory Terrain",
      "Ice Storm",
      "Locate Creature",
      "Phantasmal Killer",
      "Polymorph",
      "Private Sanctum",
      "Resilient Sphere",
      "Secret Chest",
      "Stone Shape",
      "Stoneskin",
      "Wall of Fire"
    ],
    "7": [
      "Arcane Sword",
      "Conjure Celestial",
      "Delayed Blast Fireball",
      "Divine Word",
      "Etherealness",
      "Finger of Death",
      "Fire Storm",
      "Forcecage",
      "Magnificent Mansion",
      "Mirage Arcane",
      "Plane Shift",
      "Prismatic Spray",
      "Project Image",
      "Regenerate",
      "Resurrection",
      "Reverse Gravity",
      "Sequester",
      "Simulacrum",
      "Symbol",
      "Teleport"
    ],
    "9": [
      "Astral Projection",
      "Foresight",
      "Gate",
      "Imprisonment",
      "Mass Heal",
      "Meteor Swarm",
      "Power Word Kill",
      "Prismatic Wall",
      "Shapechange",
      "Storm of Vengeance",
      "Time Stop",
      "True Polymorph",
      "True Resurrection",
      "Weird",
      "Wish"
    ],
    "6": [
      "Blade Barrier",
      "Chain Lightning",
      "Circle of Death",
      "Conjure Fey",
      "Contingency",
      "Create Undead",
      "Disintegrate",
      "Eyebite",
      "Find the Path",
      "Flesh to Stone",
      "Forbiddance",
      "Freezing Sphere",
      "Globe of Invulnerability",
      "Guards and Wards",
      "Harm",
      "Heal",
      "Heroes' Feast",
      "Instant Summons",
      "Irresistible Dance",
      "Magic Jar",
      "Mass Suggestion",
      "Move Earth",
      "Planar Ally",
      "Programmed Illusion",
      "Sunbeam",
      "Transport via Plants",
      "True Seeing",
      "Wall of Ice",
      "Wall of Thorns",
      "Wind Walk",
      "Word of Recall"
    ]
  },
  "srd-2024": {
    "2": [
      "Acid Arrow",
      "Aid",
      "Alter Self",
      "Animal Messenger",
      "Arcane Lock",
      "Arcanist's Magic Aura",
      "Augury",
      "Barkskin",
      "Blindness/Deafness",
      "Blur",
      "Calm Emotions",
      "Continual Flame",
      "Darkness",
      "Darkvision",
      "Detect Thoughts",
      "Dragon's Breath",
      "Enhance Ability",
      "Enlarge/Reduce",
      "Enthrall",
      "Find Steed",
      "Find Traps",
      "Flame Blade",
      "Flaming Sphere",
      "Gentle Repose",
      "Gust of Wind",
      "Heat Metal",
      "Hold Person",
      "Invisibility",
      "Knock",
      "Lesser Restoration",
      "Levitate",
      "Locate Animals or Plants",
      "Locate Object",
      "Magic Mouth",
      "Magic Weapon",
      "Mind Spike",
      "Mirror Image",
      "Misty Step",
      "Moonbeam",
      "Pass without Trace",
      "Phantasmal Force",
      "Prayer of Healing",
      "Protection from Poison",
      "Ray of Enfeeblement",
      "Rope Trick",
      "Scorching Ray",
      "See Invisibility",
      "Shatter",
      "Shining Smite",
      "Silence",
      "Spider Climb",
      "Spike Growth",
      "Spiritual Weapon",
      "Suggestion",
      "Warding Bond",
      "Web",
      "Zone of Truth"
    ],
    "0": [
      "Acid Splash",
      "Chill Touch",
      "Dancing Lights",
      "Druidcraft",
      "Eldritch Blast",
      "Elementalism",
      "Fire Bolt",
      "Guidance",
      "Light",
      "Mage Hand",
      "Mending",
      "Message",
      "Minor Illusion",
      "Poison Spray",
      "Prestidigitation",
      "Produce Flame",
      "Ray of Frost",
      "Resistance",
      "Sacred Flame",
      "Shillelagh",
      "Shocking Grasp",
      "Sorcerous Burst",
      "Spare the Dying",
      "Starry Wisp",
      "Thaumaturgy",
      "True Strike",
      "Vicious Mockery"
    ],
    "1": [
      "Alarm",
      "Animal Friendship",
      "Bane",
      "Bless",
      "Burning Hands",
      "Charm Person",
      "Chromatic Orb",
      "Color Spray",
      "Command",
      "Comprehend Languages",
      "Create or Destroy Water",
      "Cure Wounds",
      "Detect Evil and Good",
      "Detect Magic",
      "Detect Poison and Disease",
      "Disguise Self",
      "Dissonant Whispers",
      "Divine Favor",
      "Divine Smite",
      "Ensnaring Strike",
      "Entangle",
      "Expeditious Retreat",
      "Faerie Fire",
      "False Life",
      "Feather Fall",
      "Find Familiar",
      "Floating Disk",
      "Fog Cloud",
      "Goodberry",
      "Grease",
      "Guiding Bolt",
      "Healing Word",
      "Hellish Rebuke",
      "Heroism",
      "Hex",
      "Hideous Laughter",
      "Hunter's Mark",
      "Ice Knife",
      "Identify",
      "Illusory Script",
      "Inflict Wounds",
      "Jump",
      "Longstrider",
      "Mage Armor",
      "Magic Missile",
      "Protection from Evil and Good",
      "Purify Food and Drink",
      "Ray of Sickness",
      "Sanctuary",
      "Searing Smite",
      "Shield",
      "Shield of Faith",
      "Silent Image",
      "Sleep",
      "Speak with Animals",
      "Thunderwavea",
      "Unseen Servant"
    ],
    "8": [
      "Animal Shapes",
      "Antimagic Field",
      "Antipathy/Sympathy",
      "Befuddlement",
      "Clone",
      "Control Weather",
      "Demiplane",
      "Dominate Monster",
      "Earthquake",
      "Glibness",
      "Holy Aura",
      "Incendiary Cloud",
      "Maze",
      "Mind Blank",
      "Power Word Stun",
      "Sunburst",
      "Tsunami"
    ],
    "3": [
      "Animate Dead",
      "Beacon of Hope",
      "Bestow Curse",
      "Blink",
      "Call Lightning",
      "Clairvoyance",
      "Conjure Animals",
      "Counterspell",
      "Create Food and Water",
      "Daylight",
      "Dispel Magic",
      "Fear",
      "Fireball",
      "Fly",
      "Gaseous Form",
      "Glyph of Warding",
      "Haste",
      "Hypnotic Pattern",
      "Lightning Bolt",
      "Magic Circle",
      "Major Image",
      "Mass Healing Word",
      "Meld into Stone",
      "Nondetection",
      "Phantom Steed",
      "Plant Growth",
      "Protection from Energy",
      "Remove Curse",
      "Revivify",
      "Sending",
      "Sleet Storm",
      "Slow",
      "Speak with Dead",
      "Speak with Plants",
      "Spirit Guardians",
      "Stinking Cloud",
      "Tiny Hut",
      "Tongues",
      "Vampiric Touch",
      "Water Breathing",
      "Water Walk",
      "Wind Wall"
    ],
    "5": [
      "Animate Objects",
      "Antilife Shell",
      "Arcane Hand",
      "Awaken",
      "Cloudkill",
      "Commune",
      "Commune with Nature",
      "Cone of Cold",
      "Conjure Elemental",
      "Contact Other Plane",
      "Contagion",
      "Creation",
      "Dispel Evil and Good",
      "Dominate Person",
      "Dream",
      "Flame Strike",
      "Geas",
      "Greater Restoration",
      "Hallow",
      "Hold Monster",
      "Insect Plague",
      "Legend Lore",
      "Mass Cure Wounds",
      "Mislead",
      "Modify Memory",
      "Passwall",
      "Planar Binding",
      "Raise Dead",
      "Reincarnate",
      "Scrying",
      "Seeming",
      "Summon Dragon",
      "Telekinesis",
      "Telepathic Bond",
      "Teleportation Circle",
      "Tree Stride",
      "Wall of Force",
      "Wall of Stone"
    ],
    "4": [
      "Arcane Eye",
      "Aura of Life",
      "Banishment",
      "Black Tentacles",
      "Blight",
      "Charm Monster",
      "Compulsion",
      "Confusion",
      "Conjure Minor Elementals",
      "Conjure Woodland Beings",
      "Control Water",
      "Death Ward",
      "Dimension Door",
      "Divination",
      "Dominate Beast",
      "Fabricate",
      "Faithful Hound",
      "Fire Shield",
      "Freedom of Movement",
      "Giant Insect",
      "Greater Invisibility",
      "Guardian of Faith",
      "Hallucinatory Terrain",
      "Ice Storm",
      "Locate Creature",
      "Phantasmal Killer",
      "Polymorph",
      "Private Sanctum",
      "Resilient Sphere",
      "Secret Chest",
      "Stone Shape",
      "Stoneskin",
      "Vitriolic Sphere",
      "Wall of Fire"
    ],
    "7": [
      "Arcane Sword",
      "Conjure Celestial",
      "Delayed Blast Fireball",
      "Divine Word",
      "Etherealness",
      "Finger of Death",
      "Fire Storm",
      "Forcecage",
      "Magnificent Mansion",
      "Mirage Arcane",
      "Plane Shift",
      "Prismatic Spray",
      "Project Image",
      "Regenerate",
      "Resurrection",
      "Reverse Gravity",
      "Sequester",
      "Simulacrum",
      "Symbol",
      "Teleport"
    ],
    "9": [
      "Astral Projection",
      "Foresight",
      "Gate",
      "Imprisonment",
      "Mass Heal",
      "Meteor Swarm",
      "Power Word Heal",
      "Power Word Kill",
      "Prismatic Wall",
      "Shapechange",
      "Storm of Vengeance",
      "Time Stop",
      "True Polymorph",
      "True Resurrection",
      "Weird",
      "Wish"
    ],
    "6": [
      "Blade Barrier",
      "Chain Lightning",
      "Circle of Death",
      "Conjure Fey",
      "Contingency",
      "Create Undead",
      "Disintegrate",
      "Eyebite",
      "Find the Path",
      "Flesh to Stone",
      "Forbiddance",
      "Globe of Invulnerability",
      "Guards and Wards",
      "Harm",
      "Heal",
      "Heroes' Feast",
      "Instant Summons",
      "Irresistible Dance",
      "Magic Jar",
      "Mass Suggestion",
      "Move Earth",
      "Planar Ally",
      "Programmed Illusion",
      "Sunbeam",
      "Transport via Plants",
      "True Seeing",
      "Wall of Ice",
      "Wall of Thorns",
      "Wind Walk",
      "Word of Recall"
    ]
  }
};

// Source mapping and other data stays the same
const sourceMapping = {
    "wotc-srd": {
        directory: "5.1_srd_(d&d_2014)",
        displayName: "D&D 2014 (5.1 SRD)"
    },
    "srd-2024": {
        directory: "5.2_srd_(d&d_2024)", 
        displayName: "D&D 2024 (5.2 SRD)"
    },
    "dmag": {
        directory: "deep_magic_5e",
        displayName: "Deep Magic 5e"
    },
    "a5e": {
        directory: "level_up_advanced_5e",
        displayName: "Level Up Advanced 5e"
    }
};

const scrollStats = {
    "0": { rarity: "Common", dc: 13, attack: 5, price: 30 },
    "1": { rarity: "Common", dc: 13, attack: 5, price: 50 },
    "2": { rarity: "Uncommon", dc: 13, attack: 5, price: 200 },
    "3": { rarity: "Uncommon", dc: 15, attack: 7, price: 300 },
    "4": { rarity: "Rare", dc: 15, attack: 7, price: 2000 },
    "5": { rarity: "Rare", dc: 17, attack: 9, price: 3000 },
    "6": { rarity: "Very Rare", dc: 17, attack: 9, price: 20000 },
    "7": { rarity: "Very Rare", dc: 18, attack: 10, price: 25000 },
    "8": { rarity: "Very Rare", dc: 18, attack: 10, price: 30000 },
    "9": { rarity: "Legendary", dc: 19, attack: 11, price: 100000 }
};

const rarityToLevels = {
    "common": ["0", "1"],
    "uncommon": ["2", "3"],
    "rare": ["4", "5"],
    "very-rare": ["6", "7", "8"],
    "legendary": ["9"],
    "any": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
};

function spellNameToUrl(spellName) {
    return spellName
        .toLowerCase()
        .replace(/'/g, '')
        .replace(/\//g, '')
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '');
}

function getSpellLink(spellName, source) {
    let urlName = spellNameToUrl(spellName);
    
    if (source === 'a5e') {
        urlName += '-a5e';
    }
    
    const sourceData = sourceMapping[source];
    if (!sourceData) {
        console.warn(`Unknown source: ${source}`);
        return '#';
    }
    return `../../spells/html/${sourceData.directory}/${urlName}.html`;
}

function getSpellsFromSource(source, level) {
    if (!spellIndex[source] || !spellIndex[source][level]) {
        return [];
    }
    return spellIndex[source][level];
}
